# Generated by Django 2.2.12 on 2022-02-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20211221_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书'},
        ),
    ]
