# Generated by Django 2.2.12 on 2021-12-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20211214_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='mark_price',
            new_name='market_price',
        ),
    ]
